### ISSUE TITLE
Frequent mousewheel events may scroll the document beneath

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#167]
This occurs especially in Safari. If you scroll the dropdown (months) fast with mousewheel/touchpad, sometimes the whole document below might end up scrolling.

Easiest fix for this is probably to preventDefault on the mousewheel events at date-picker level and stopping the propagation of the mousewheel events at date-picker-overlay level.

**Comment by platosha** [comment]
Won't fix.

The solution suggested in the ticket by @tomivirkki doesn't work. When mouse wheel scrolling leaks to document, there's no wheel events dispatched about. Therefore we can’t prevent it by calling `preventDefault()` inside wheel event handlers.

The only working solution found so far is to add `overflow: hidden;` to body styles. We decided to avoid that because of side-effects.
