### ISSUE TITLE
Let the developer customize the input area

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#185]
The same feature as https://github.com/vaadin/vaadin-combo-box/issues/198

**Comment by tehapo** [comment]
The work done for `vaadin-combo-box` can be found in the `feature/custom-input` branch.
https://github.com/vaadin/vaadin-combo-box/tree/feature/custom-input

**Comment by tehapo** [comment]
While planning the developer usability tests, we started thinking that `vaadin-date-picker` should have the same API as the `vaadin-combo-box` element.

This would mean that we need to create a `vaadin-date-picker-light` also. We can't get rid of all `paper-*` imports because of the full screen mode, but that could be planned later. At least we should define the same API for both.

**Comment by manolo** [comment]
Working on the refactoring of vaadin-date-picker as a behaviour imported in vaadin-date-picker and vaadin-date-picker-light to follow the same pattern than combo-box
