### ISSUE TITLE
cannot read property of settings of undefined

### ISSUE THREAD

**Issue by bona1337** [vaadin/vaadin-date-picker#205]
hello there,
the best datepicker I've seen so far for angular 2 projects! thats why I really wanna use it ... butttt I have some integration errors..
I'm using the mgechev/angular2-seed project... 
I installed the @vaadin/angular2-polymer and webcomponentsjs via npm... 
loading them in the seed.config..
and added the bower packages... 

as soon as I hit npm start.. everything compiles fine.. but I have an error in my console and i cannot figure out where it comes from

102 Error: TypeError: Cannot read property 'Settings' of undefined(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

I added a plunker with my component and the seed&config files...
https://plnkr.co/edit/qsjIAqZ146nrsaeqoIzs?p=catalogue

thats actually my first bower package.. so I'm not sure what exactly I'm missing out here

any ideas on this one?

**Comment by platosha** [comment]
Hello, the cause is that Polymer was not imported.

Just installing bower packages is not enough. You should also:

1. Import the Polymer elements you need, such as Vaadin Date Picker, by adding the HTML imports,

2. Make sure that the Angular 2 application code is imported __after__ the HTML imports are loaded and the Polymer elements are registered.

Importing Polymer elements with HTML imports will also import their dependencies, including the Polymer library itself. This will resolve the error you have.

Please see the [Step 4 of the Angular 2 with Polymer Elements Tutorial](https://vaadin.com/docs/-/part/elements/angular2-polymer/tutorial-index.html#vaadin-angular2-polymer.tutorial.polymer) for the detailed instructions. These tutorial instructions are based on the Angular 2 QuickStart application code. We don’t have the instructions targeted for `mgechev/angular2-seed`-based projects. In our tutorial, we place HTML imports in the head section of the index.html file, and we postpone the `System.import('app')` call by wrapping it into an event listener for `WebComponentsReady` event. These implementation details might be different for your project base, though the requirements behind them are the same.

Apart from that, the error message you have is indeed not descriptive and unhelpful. This is an issue of the `@vaadin/angular2-polymer` package rather than of the Date Picker element. Filed there: vaadin/angular2-polymer#42
