### ISSUE TITLE
Only show one month at a time (max-height for the overlay)

### ISSUE THREAD

**Issue by jay8t6** [vaadin/vaadin-date-picker#223]
Traditional datepickers show one month at a time. It would be great if we could add a property that would show one month at a time. Is it possible to add?

**Comment by jouni** [comment]
You can set a max-height for the overlay element so that it only fits one month.
```html
<style is="custom-style">
:root {
  --vaadin-date-picker-overlay: 360px;
}
</style>
```

On small viewports the date picker still covers the whole page.

I would suggest not to make the overlay so narrow that only one month is visible, because then the user doesn’t have any visual cue that they can scroll the overlay to see prev/next months.

Currently the overlay is only restricted by the viewport height, but I think we want to set some default max-height for it, so that you see roughly 2 months at max (the current month completely, and half of the prev and next months).

**Comment by jay8t6** [comment]
setting max height worked fine. Thanks! And I agree with you on setting the default max-height. Thanks for adding it to the enhancements.

**Comment by jouni** [comment]
This is fixed now in v3 (currently in beta).
