### ISSUE TITLE
JS Date object might break under different conditions.

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-date-picker#274]
The Date object might break depending on how it was constructed.

See:
http://www.slideshare.net/MaggiePint/date-and-time-momentjs-edition
https://www.youtube.com/watch?v=ieIzNP6gKqU

**Comment by platosha** [comment]
I doubt if there are any date-picker issues related with this. Any suggestions on what exactly to check?

We don’t use `Date` object for storing anything, and don’t rely on its unreliable parser as well. The `value` property, which is the picker’s main outcome, is a string in ISO format, so we don’t encourage users to store `Date` objects in their applications as well.

`Date` objects are used as an _internal representation_, and only in local time form, just for maths and passthrough, basically. We agreed to avoid adding external dependencies, such as `Moment.js`, previously.

**Comment by tomivirkki** [comment]
One thing we could do is to improve `i18n`'s formatting and parsing API's so that developer doesn't need to communicate with `vaadin-date-picker` with Date objects but in 'YYYY-MM-DD' formatted Strings.

In practice
 - `formatDate` should pass 'YYYY-MM-DD' formatted date as parameter (instead of a Date object)
 - `parseDate` should expect 'YYYY-MM-DD' formatted date as return value (instead of a Date object)

**Comment by vicsstar** [comment]
What do you think; should this fix target "next" or "master" branch?

**Comment by tomivirkki** [comment]
Should target the new element structure

**Comment by vicsstar** [comment]
So "next".

**Comment by tomivirkki** [comment]
At the moment the `next` branch does have the new structure yes, but that might change any time since we're in the process of merging the branches to `master`. This discussion shouldn't take place in ticket comments.
