### ISSUE TITLE
Inconsistent keyboard navigation when opening popup

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-date-picker#301]
### Description
When a date field is empty, you can press arrow down to open the popup and then navigate to yesterday using arrow left.

If the date field is set the today's date, pressing arrow down still opens the popup but arrow left does not navigate to yesterday.

If you happen to do arrow up or down before arrow left, then arrow left works in both cases.
### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari

**Comment by Saulis** [comment]
Since `v1.2.0-beta1` we've improved on how the focus is displayed – in the case when a date is already selected when the overlay gets opened, the focus is in the input field instead of the selected date (which has a lighter color than when focused).

I agree that it might not be obvious for all users, not sure if there has already been discussion behind where the focus should go when overlay is opened using arrow keys? ping @jouni @tomivirkki

**Comment by jouni** [comment]
That seems like something we haven’t considered properly, thanks for the report!

I think it should work the same in both cases: pressing arrow up/down should always focus the overlay immediately.

**Comment by tomivirkki** [comment]
While fixing this, also remove functionality that unnecessarily focuses the overlay on left/right key on an empty input
