### ISSUE TITLE
Add year navigation

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-date-picker#35]
Let’s start by drawing mockups of the few new options that we’ve discussed (in addition to the previous separate year list view):
- Year scroller next to the month scroller, always visible if there is enough horizontal screen space
   - Ensure proper touch targets for the year numbers (users can tap in between years as well to jump to "june/july" immediately)
- When not enough horizontal space:
  - Have the year scroller become visible on top of the month scroller. Once scrolling stops, hide it after a short delay
  - Have an explicit toggling for the year scroller (the year number in the header)
     - The year scroller overlaps the month scroller
     - The year scroller pushes the month scroller sideways

**Comment by tuomasnironen** [comment]
[Initial artboards for year select](https://drive.google.com/drive/u/0/folders/0BzkWbWvgmkIxR2ZKSnpTN1N6Njg) added to Google Drive.

**Comment by tehapo** [comment]
Here are four initial prototypes, which are not very polished but maybe are still already worth sharing here.

* http://wc.demo.vaadin.com/year-picker1/mobile.html
  * Overlays the year scroller on top of the months.
  * Display a hint of something when scrolling a bit.
  * Open the full year scroller when scrolling fast enough.
  * Hide after some inactivity.

---

* http://wc.demo.vaadin.com/year-picker2/mobile.html
  * Pushes the months aside.
  * Open the full year scroller when swiping anywhere.
  * Custom implementation of the swipe gesture, needs work to feel native.

---

* http://wc.demo.vaadin.com/year-picker3/mobile.html
  * Overlays the year scroller on top of the months.
  * Open the full year scroller when swiping on right side (or tapping the toolbar).
  * Uses paper-drawer-panel.

---

* http://wc.demo.vaadin.com/year-picker4/mobile.html
  * Scales the months smaller to make room for the year scroller.
  * Open the full year scroller when swiping anywhere (or tapping the toolbar).
  * Custom implementation of the swipe gesture, needs work to feel native.

**Comment by tuomasnironen** [comment]
Year picker #1:
* I like this proto with the hinting effect as the best starting point (y)
* Should we make the year panel appear a bit sooner when scrolling?
* If you stop scrolling, the year panel should hide after a short delay
* Enable showing/hiding the panel instantly with a horizontal swipe?
* Enable tapping/clicking on a year to reposition the scroller immediately (keep the topmost month in the scroller before tapping, e.g. "August 2016" -> tap 1977 -> "August 1977" at the top)
* I would replace the year counter bar at the top with fixing the topmost month label at the top, accompanied by the year number (e.g. "February 2016"). Also enable the year scrolling panel to extend all the way to the top inside date picker container.
  * Maybe we have to align the month name + year number string to the left. The text might go under the appearing year panel with some languages with long month names on small screens
* When the date picker is opened, it would be useful to scroll the page so that the input is placed at the top and there is maximum vertical space available for the date grid scroller. Even with the iPhone6 this proto with some content above the date picker, there seems to be too little vertical space left for the date grid scroller.
* Maybe the year panel row height should be more compact than suggested in the design. Then again, if it makes the grid scrolling disturbingly fast, a good balance should be considered.

Year picker #2:
* The push is a good effect only if we have the fullscreen mode available on mobile. Now the effect seems a bit wrong inside the modal-like container.

Year picker #3:
* Meh. I think the visual and usability advantages found in other prototypes outweigh this one.

Year picker #4:
* Scaling the date grid seems like a nice idea. Just wondering how small it will look on an iPhone5 sized screen and with the week numbers aside.
* The swipe gesture should be a bit more responsive for short quick swipes. Now it takes a long and determined dragswipe to unhide the year panel.

**Comment by tuomasnironen** [comment]
Additional designs (fixed year+month bar with push-swipe 3 alternative themes):
* https://drive.google.com/open?id=0BzkWbWvgmkIxWVItR3pOd0E2a28
* https://drive.google.com/open?id=0BzkWbWvgmkIxSWtMT1VieDZfTm8
* https://drive.google.com/open?id=0BzkWbWvgmkIxTkpheTVwUGtQMWc
