### ISSUE TITLE
Typing the date in the input with keyboard does not change focused date

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-date-picker#438]
It seems that it's necessary to have the overlay closed to see the problem in action

http://recordit.co/FuRJWJESMO

**Comment by jouni** [comment]
I don’t fully understand the issue. Could describe it in more detail, what steps should be done to reproduce it?

**Comment by marcushellberg** [comment]
The issue is that keyboard input changes the selected date only when the pop-up is open. If the pop-up is closed and the date is modified, the popup doesn't reflect that change once opened.

**Comment by vicsstar** [comment]
I see what the video tried to describe but, I don't see the issue with that behaviour, looks perfect to me. Pressing the ESC key closes the date-picker and resets the value to the former, pressing the ENTER key closes the date-picker and retains the current value.

Please tell me, did I get that right? Isn't that the expected behaviour?

**Comment by tomivirkki** [comment]
The issue occurs at 0:27. When he changes the day value in the input field from 26 to 27, focused day on the overlay is still positioned at 26.

**Comment by vicsstar** [comment]
I understand the issue now.
