### ISSUE TITLE
Invalid date picker doesn't get revalidated

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#490]
1. Type "foobar" in the input field
2. Click outside the overlay to get it closed and invalid
3. Pick a valid date for date picker
-> Still appears invalid

**Comment by web-padawan** [comment]
The reason is [this line](https://github.com/vaadin/vaadin-text-field/blob/master/src/vaadin-text-field-mixin.html#L243) in the text field `checkValidity` method. It simply returns false once invalid and therefore prevents marking correct date as valid. 
I am wondering if we should ever check input validity here?
