### ISSUE TITLE
No matching version found for @vaadin/vaadin-material-styles@^1.1.0-beta1

### ISSUE THREAD

**Issue by craPkit** [vaadin/vaadin-date-picker#591]
### Description
`npm i @vaadin/vaadin-date-picker`
yields
"No matching version found for @vaadin/vaadin-material-styles@^1.1.0-beta1"

### Expected outcome
`npm i @vaadin/vaadin-date-picker`
installs successfully

### Actual outcome
"No matching version found for @vaadin/vaadin-material-styles@^1.1.0-beta1"

Tested the installation via npm just now.

**Comment by web-padawan** [comment]
Hi, we are currently in progress of releasing everything and some conflicts like this might happen. Apologies for the inconvenience, in the meanwhile you can temporarily downgrade to `pre` versions, until we publish everything as betas.

See the working example: https://github.com/web-padawan/polymer3-webpack-starter/blob/master/package.json#L21

I will close the issue once we confirm the components are published and can be installed.

**Comment by craPkit** [comment]
No worries, just wanted to make sure this doesn't go unnoticed.
`pre` works and I'm totally fine with that for the moment. Thanks!

**Comment by web-padawan** [comment]
The following components are published and can be used:

-  `@vaadin/vaadin-material-styles` 1.1.0-beta1
-  `@vaadin/vaadin-date-picker` 3.2.0-beta2

Note that we still have not published `@vaadin/vaadin-grid` so if you also use that component, please delay your upgrade to avoid conflicts. Otherwise, you should be able to upgrade now.
