### ISSUE TITLE
The calendar icon is misaligned vertically

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-date-picker#602]
### Description

The calendar icon is misaligned vertically:

![image](https://user-images.githubusercontent.com/6059356/44980103-8ad53e00-af77-11e8-8f3b-45a60114692e.png)

### Live Demo
https://cdn.vaadin.com/vaadin-date-picker/3.2.0/demo/#date-picker-basic-demos

Setting `display: flex` on `.toggle-button` or `display: block` on `.toggle-button::before` seems to help.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment]
`vertical-align: top` on the pseudo-element also fixes it, or setting `font-family: lumo-icons` on the toggle-button element.

The problem stems from the [font icon baseline settings](https://github.com/vaadin/vaadin-lumo-styles/blob/master/gulpfile.js#L173-L174) which cause the baseline of the icon to be different from the main font-family used in the input field.

It doesn’t really make much difference which fix is used. Using block formatting for the icon would probably be safest, though, so that if a developer uses a different icon font they won’t get any surprises.

**Comment by platosha** [comment]
Interestingly, `<vaadin-combo-box>` does not have this issue, despite of sharing seemingly the same styles and the same icon font file.

**Comment by heruan** [comment]
Any update on this? It's pretty evident when a `time-picker` is set aside a `date-picker`: the clock icon is correctly aligned, while the calendar isn't.
