### ISSUE TITLE
custom format not supported

### ISSUE THREAD

**Issue by punkratz312** [vaadin/vaadin-date-picker#616]
Unfortunately the component does not handle date custom formation correctly. The date looks in the ui like expected but it´s saved in internal non custom format:

![image](https://user-images.githubusercontent.com/8830888/48139229-42533d00-e2a6-11e8-8769-4e73aab46be1.png)

![image](https://user-images.githubusercontent.com/8830888/48139570-16848700-e2a7-11e8-8112-3b9765e82d39.png)

Heres my custom formation:
![image](https://user-images.githubusercontent.com/8830888/48139315-7dee0700-e2a6-11e8-95bb-f887451aaf65.png)

Further more the component does not accept pre defined values. If the bound value actually has a value it´s getting ignored and not preset in the picker. Non of the formation methods gets called to format the given value. 👎👎👎 

*Edit: If the date has the expected format 2018-11-11 it works. Other date formats get not accepted... 👎 👎 👎 👎 👎

**Comment by tomivirkki** [comment]
Please note that the `value` property is _always_ in ISO 8601 format as documented in the [API](https://cdn.vaadin.com/vaadin-date-picker/3.3.0/#/elements/vaadin-date-picker#property-value). 

Formatting the date is just about presentation.

**Comment by punkratz312** [comment]
I feel very sorry for this questionable approach. Why forcing the user to make a longer work around which I already did, if you have already got the date in preferred form. 

Thanks for the reply.

**Comment by tomivirkki** [comment]
The approach should be familiar to web developers as the native `<input type="date">` exposes its "value" exactly in the same standard format. [The presenation format of the native date picker is also different from the value format](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Value). Because of this alignment, `<vaadin-date-picker>` works as a drop-in replacement for the native date picker.

Having the value in language-agnostic standard format enables its use for different purposes also. For example libraries such as Moment.js understand standard date formats better than something formatted in an arbitrary locale, and if your UI supports more than one language, a value formatted and then stored in some specific locale wouldn't work with users of other languages. 

For example, if a date selected by a Chinese user was stored to database in Chinese format, a German user would have hard time understanding it. Editing the Chinese formatted value wouldn't really work either as you couldn't easily import the date value back to a "German speaking" date picker.

Duplicate of https://github.com/vaadin/vaadin-date-picker/issues/365
