### ISSUE TITLE
Date picker is shown under toolbar in paper-header-panel on iOS

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#66]
![img_0526](https://cloud.githubusercontent.com/assets/883698/13303584/0c803756-db05-11e5-8bff-9f39ba76984c.jpg)

**Comment by tomivirkki** [comment]
This is due to a known problem in iOS Safari http://weblog.west-wind.com/posts/2015/Jun/05/IPad-Scroll-Issues-with-Fixed-Content

Removing the `-webkit-overflow-scrolling: touch;` or `overflow` rules from paper-header-panel is a workaround for now but I don't really see anything that can be done inside vaadin-date-picker to fix this. 

The overlay could be moved outside the component itself (like vaadin-combo-box does) but this would result into nasty style scope issues (much bigger an issue for date-picker than for combo-box) so it might not really be a viable option.

**Comment by vaadin-marcus** [comment]
I still think that this is something that we need to have a solution for. I assume that a big portion of Polymer apps are using the header panel as PSK comes with it.

**Comment by tomivirkki** [comment]
Added a PR for fixing this with a nasty hack: Whenever the date picker dropdown is opened, it traverses all its ancestor elements and sets an inline "webkit-overflow-scrolling: auto" for any one with "touch" as the existing value.

The original values are restored on dropdown close / component detach.

Note:  This workaround will work as long as the browser doesn't support and use native shadow dom
