### ISSUE TITLE
Adding a disabled date picker logs warnings

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-date-picker#754]
```
[http-nio-8080-exec-878] WARN com.vaadin.flow.server.communication.rpc.MapSyncRpcHandler - Property update request for disabled element is received from the client side. The property is 'value'. Request is ignored.
[http-nio-8080-exec-878] WARN com.vaadin.flow.server.communication.rpc.MapSyncRpcHandler - Property update request for disabled element is received from the client side. The property is 'opened'. Request is ignored.
```

**Comment by web-padawan** [comment]
Closing as duplicate of https://github.com/vaadin/flow/issues/8848 which will be soon fixed by https://github.com/vaadin/vaadin-flow-components/pull/512.

**Comment by pleku** [comment]
@web-padawan I'm not entirely sure if this is actually fixed by vaadin/vaadin-flow-components#512 as I didn't test this - to my understanding, if the property ^ defaults are wrong on the server side, then this will be still logged.

The fix I did was taking care of two empty RPC calls done with `executeJS` calls that were not even needed.

**Comment by web-padawan** [comment]
Thanks. I will double check when the fix is merged. Not sure if we should reopen this and mark as a bug?

**Comment by pleku** [comment]
I'll check it later today based on my changes. If it is still valid, yes then it should be treated as a bug as it gives a bad impression.

**Comment by pleku** [comment]
I can confirm that after vaadin/vaadin-flow-components#512 there were no warnings logged for a disabled `DatePicker`, so this can remain closed.

**Comment by web-padawan** [comment]
Thanks for checking this issue 🙇‍♂️
