### ISSUE TITLE
Setting Min and Max grays out all dates

### ISSUE THREAD

**Issue by damrath** [vaadin/vaadin-date-picker#772]
#### Use case:
I want to set min and max values to disable picking dates outside of the current week. 

#### Problem:
All dates are grayed out, but dates within the range of min-max are selectable, see screenshot.

#### Steps to reproduce:
```Java
DatePicker picker = new DatePicker("Date", LocalDate.now());

LocalDate currentMonday = LocalDate.now().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));
LocalDate currentFriday = LocalDate.now().with(TemporalAdjusters.nextOrSame(DayOfWeek.FRIDAY));

picker.setLocale(Locale.GERMANY);
picker.setMin(currentMonday);
picker.setMax(currentFriday);
```

#### Expected Behavior:
All dates except the ones within the range [min, max] are grayed out.

#### Screenshot
![datepicker](https://user-images.githubusercontent.com/27375330/41226007-7d8dba22-6d70-11e8-94a4-14a227d613db.png)

#### Browsers tested and affected:
- Firefox Quantum 60.0.2 for Manjaro Linux
- Chromium 67.0.3396.79 (Official Build) Arch Linux (64-bit)

#### Version
vaadin.version in POM: 10.0.0.rc2

**Comment by web-padawan** [comment]
I could not reproduce this issue with `vaadin-datepicker-flow` 2.2.0 (part of Vaadin 14.4.0)

Tested by updating the [demo code](https://github.com/vaadin/vaadin-date-picker-flow/blob/a69c18dba81a73b928b1cbf95ed4d463d937be68/vaadin-date-picker-flow-demo/src/main/java/com/vaadin/flow/component/datepicker/demo/DatePickerView.java#L75-L77) based on the provided example:

```
DatePicker valueDatePicker = new DatePicker();
LocalDate now = LocalDate.now();
valueDatePicker.setValue(now);

LocalDate currentMonday = LocalDate.now().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));
LocalDate currentFriday = LocalDate.now().with(TemporalAdjusters.nextOrSame(DayOfWeek.FRIDAY));

valueDatePicker.setLocale(Locale.GERMANY);
valueDatePicker.setMin(currentMonday);
valueDatePicker.setMax(currentFriday);
```

As you can see on the screenshot, the date picker calendar looks as expected:

![Screenshot 2020-10-08 at 13 37 38](https://user-images.githubusercontent.com/10589913/95448116-7c825900-096b-11eb-91f0-7323c8d12308.png)


Closing as no longer reproducible. Please submit a new issue if the problem is still valid.
